### PR TITLE
Fix edge collision, Fixes #56

### LINKED ISSUE #56: Player gets stuck on collider edges

### PR DESCRIPTION
**Pull request by bhatnathan**

### CODE REVIEW

**Comment by bhatnathan** [comment]
These changes need to be made to the pushable block as well since I imagine it has the same problem.

**Comment by bhatnathan** [comment]
I'd also let the Rigidbody as well as the LayerMask for groundlayer be fetched through code rather than the editor, since doing multiple hookups for the same thing is not really desired behaviour.

Rigidbody can be fetched with GetComponent, and groundLayer can be fetched from DynamicObject.

**Comment by CogEpitome** [comment]
> I'd also let the Rigidbody as well as the LayerMask for groundlayer be fetched through code rather than the editor, since doing multiple hookups for the same thing is not really desired behaviour.
> 
> Rigidbody can be fetched with GetComponent, and groundLayer can be fetched from DynamicObject.

Agreed, that's a relic from when the new ground check used a separate relativelayerquery check and had to be in a different gameobject.

**Comment by CogEpitome** [comment]
Epic, I pulled the changes and it looks great!
An SFX bug is that the sphere collider jumps a little instead of getting stuck on edges so the jump sfx keeps playing

**Pull request merged**
